export enum Topic {
  HISTORY='HISTORY',
  CHEMISTRY='CHEMISTRY',
  PHYSICS='PHYSICS',
  BIOLOGY='BIOLOGY',
  ANIMALS='ANIMALS',
  PLANTS='PLANTS',
  GEOGRAPHY='GEOGRAPHY',
  LITERATURE='LITERATURE',
  INFORMATION_TECHNOLOGY='INFORMATION_TECHNOLOGY',
  RANDOM='RANDOM'
}
